version: '2.1'
orbs:
  go: circleci/go@1.7.3
jobs:
  build:
    executor:
      name: go/default
      tag: '1.16'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          race: true
workflows:
  main:
    jobs:
      - build
